library(ggplot2)
library(dplyr)

fp <- file("moby.txt", "r", blocking = FALSE)
moby <- readLines(fp)
close(fp)
moby <- paste0(moby, sep=" ", collapse="")
x <- as.integer(charToRaw(moby))
df <- data.frame(ascii = x)
dat <- df %>% group_by(ascii) %>% summarize(count=length(ascii))
o <- order(dat$count, decreasing=T)
freq <- data.frame(ascii=dat$ascii[o], count=dat$count[o])
freq$char <- rawToChar(as.raw(freq$ascii), multiple=T)
freq$hex <- as.hexmode(freq$ascii)
freq$ascii <- factor(freq$ascii)
freq$ascii <- reorder(freq$ascii, -freq$count)
rm(x)
rm(df)
rm(dat)

p <- ggplot(freq, aes(x=ascii, y=count)) + scale_x_discrete(labels=freq$char) + geom_col()
print(p)
