library(ggplot2)
library(dplyr)

fp <- file("moby.txt", "r", blocking = FALSE)
moby <- readLines(fp)
close(fp)
moby <- paste0(moby, sep=" ", collapse="")
x <- factor(as.integer(charToRaw(moby)))
df <- data.frame(char = x)
dat <- df %>% group_by(char) %>% summarize(count=length(char))
dat$char <- reorder(dat$char, -dat$count)
ggplot(dat, aes(x=char, y=count)) + geom_col()